# Generated by Django 5.1.4 on 2024-12-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
